// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoPk9Y1loMXo6TEd_qZEHCJtkWhPLTd6Q',
    appId: '1:866386657030:web:9c6dd22571d3c6b977e887',
    messagingSenderId: '866386657030',
    projectId: 'city-strides-4f1e0',
    authDomain: 'city-strides-4f1e0.firebaseapp.com',
    storageBucket: 'city-strides-4f1e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWqesXSbUA9fSKEEzJZiikyHBsroqseVU',
    appId: '1:866386657030:android:5bdf8bc019722fec77e887',
    messagingSenderId: '866386657030',
    projectId: 'city-strides-4f1e0',
    storageBucket: 'city-strides-4f1e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnW_Cwrq3y7W8vYsxBdpYd4hk1Sovhy18',
    appId: '1:866386657030:ios:3b3085f47cce573b77e887',
    messagingSenderId: '866386657030',
    projectId: 'city-strides-4f1e0',
    storageBucket: 'city-strides-4f1e0.firebasestorage.app',
    iosBundleId: 'com.example.cityStrides',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnW_Cwrq3y7W8vYsxBdpYd4hk1Sovhy18',
    appId: '1:866386657030:ios:3b3085f47cce573b77e887',
    messagingSenderId: '866386657030',
    projectId: 'city-strides-4f1e0',
    storageBucket: 'city-strides-4f1e0.firebasestorage.app',
    iosBundleId: 'com.example.cityStrides',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoPk9Y1loMXo6TEd_qZEHCJtkWhPLTd6Q',
    appId: '1:866386657030:web:7d4ee04b5319978e77e887',
    messagingSenderId: '866386657030',
    projectId: 'city-strides-4f1e0',
    authDomain: 'city-strides-4f1e0.firebaseapp.com',
    storageBucket: 'city-strides-4f1e0.firebasestorage.app',
  );
}
